version: v2
plugins:
  - remote: buf.build/community/neoeinstein-prost:v0.5.0
    out: src/gen
    # https://github.com/neoeinstein/protoc-gen-prost/tree/main/protoc-gen-prost#options
    opt:
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
      - file_descriptor_set
  - remote: buf.build/community/neoeinstein-tonic:v0.5.0
    out: src/gen
    # https://github.com/neoeinstein/protoc-gen-prost/tree/main/protoc-gen-tonic
    opt:
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
      - no_client=true
  - remote: buf.build/community/neoeinstein-prost-crate:v0.5.0
    out: src/gen
    # https://github.com/neoeinstein/protoc-gen-prost/tree/main/protoc-gen-prost-crate
    opt:
      - no_features
